<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<MinVerMinimumMajorMinor>0.0</MinVerMinimumMajorMinor>
		<MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net7.0;net8.0</TargetFrameworks>
		<LangVersion>12.0</LangVersion>
		<Platforms>AnyCPU</Platforms>
		<RootNamespace>Scaffold.Calculations</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<Title>Scaffold Calculations</Title>
		<Company>Whitby Wood</Company>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/VividOrange/SCaFFOLD/</RepositoryUrl>
		<PackageIcon>VividOrange.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MinVer" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="VividOrange.Materials" Version="0.1.0" />
		<PackageReference Include="VividOrange.Sections" Version="0.1.0" />
		<PackageReference Include="VividOrange.Sections.SectionProperties" Version="0.1.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\VividOrange.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Scaffold.Calculations.Tests" />
      <ProjectReference Include="..\Scaffold.Core\Scaffold.Core.csproj" />
    </ItemGroup>

</Project>
