<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <MinVerMinimumMajorMinor>0.12</MinVerMinimumMajorMinor>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <Version>0.12</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <RootNamespace>Scaffold</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Scaffold Core</Title>
    <Company>Whitby Wood</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/VividOrange/SCaFFOLD/</RepositoryUrl>
    <PackageIcon>VividOrange.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\VividOrange.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UnitsNet" Version="5.75.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
    <PackageReference Include="VividOrange.IGeometry" Version="1.8.0" />
    <PackageReference Include="VividOrange.ISections" Version="0.1.0" />
    <PackageReference Include="VividOrange.Profiles.Perimeter" Version="0.1.0" />
    <PackageReference Include="VividOrange.Serialization" Version="0.1.0" />
  </ItemGroup>

</Project>
