global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Linq;
global using Scaffold.Calculations.Eurocode.Concrete.Utility;
global using Scaffold.Core.Abstract;
global using Scaffold.Core.CalcValues;
global using Scaffold.Core.Enums;
global using Scaffold.Core.Exceptions;
global using Scaffold.Core.Interfaces;
global using Scaffold.Core.Models;
global using UnitsNet;
global using UnitsNet.Units;
global using Xunit;
global using ForcePerArea = UnitsNet.Pressure;
global using ForcePerAreaUnit = UnitsNet.Units.PressureUnit;
global using Moment = UnitsNet.Torque;
global using MomentPerLength = UnitsNet.TorquePerLength;
global using MomentPerLengthUnit = UnitsNet.Units.TorquePerLengthUnit;
global using MomentUnit = UnitsNet.Units.TorqueUnit;
global using Strain = UnitsNet.Ratio;
global using StrainUnit = UnitsNet.Units.RatioUnit;
global using Stress = UnitsNet.Pressure;
global using StressUnit = UnitsNet.Units.PressureUnit;
